# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_tok0_global_optspecs
	string join \n v/verbose u/ultra-compact h/help V/version
end

function __fish_tok0_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_tok0_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_tok0_using_subcommand
	set -l cmd (__fish_tok0_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c tok0 -n "__fish_tok0_needs_command" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_needs_command" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_needs_command" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_needs_command" -s V -l version -d 'Print version'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "stats" -d 'Token savings analytics'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "git" -d 'Git operations'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "read" -d 'Smart file reading'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "ls" -d 'Directory listing'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "grep" -d 'Search files'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "find" -d 'Find files'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "diff" -d 'File diff'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "smart" -d 'Smart code summary'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "proxy" -d 'Proxy passthrough (no filtering, tracking only)'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "status" -d 'Show tok0 status: version, hooks, savings, trust, extensions'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "doctor" -d 'Diagnose configuration + hook-health problems'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "rule" -d 'Inspect and test compression rules'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "init" -d 'Initialize hooks for AI tools'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "update" -d 'Check for updates'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "discover" -d 'Discover missed savings opportunities'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "rewrite" -d 'Rewrite command (used by hooks)'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "profile" -d 'Profile compression pipeline timing'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "ext" -d 'Manage extension rule packs'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "telemetry" -d 'Control anonymous telemetry (on/off/status)'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "auth" -d 'Authenticate with tok0 cloud for team analytics'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "cloud" -d 'View team dashboard (requires auth)'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "completions" -d 'Generate shell completions'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "trust" -d 'Trust a project directory for local filter rules'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "untrust" -d 'Remove trust from a project directory'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "verify" -d 'Verify hook file integrity'
complete -c tok0 -n "__fish_tok0_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -l format -r
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -l graph
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -l history
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -l daily
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand stats" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand git" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand git" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand git" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand read" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand read" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand read" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ls" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand ls" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand ls" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand grep" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand grep" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand grep" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand find" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand find" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand find" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand diff" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand diff" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand diff" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand smart" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand smart" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand smart" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand proxy" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand proxy" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand proxy" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand status" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand status" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand status" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand doctor" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand doctor" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand doctor" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -f -a "list" -d 'List all active rules (builtin + extensions + project-local)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -f -a "show" -d 'Show full config for a single rule by name'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -f -a "test" -d 'Apply a rule to stdin and print the before/after savings'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and not __fish_seen_subcommand_from list show test help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from list" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from show" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from show" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from test" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from test" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from test" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all active rules (builtin + extensions + project-local)'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show full config for a single rule by name'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from help" -f -a "test" -d 'Apply a rule to stdin and print the before/after savings'
complete -c tok0 -n "__fish_tok0_using_subcommand rule; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand init" -s g -l global
complete -c tok0 -n "__fish_tok0_using_subcommand init" -l uninstall
complete -c tok0 -n "__fish_tok0_using_subcommand init" -l show
complete -c tok0 -n "__fish_tok0_using_subcommand init" -l wizard -d 'Run the guided onboarding wizard'
complete -c tok0 -n "__fish_tok0_using_subcommand init" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand init" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand init" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand update" -l check
complete -c tok0 -n "__fish_tok0_using_subcommand update" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand update" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand update" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand discover" -l since -r
complete -c tok0 -n "__fish_tok0_using_subcommand discover" -l all
complete -c tok0 -n "__fish_tok0_using_subcommand discover" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand discover" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand discover" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand rewrite" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand rewrite" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand rewrite" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand profile" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand profile" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand profile" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -f -a "install" -d 'Install extension from a git URL'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -f -a "list" -d 'List installed extensions'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -f -a "remove" -d 'Remove an installed extension'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and not __fish_seen_subcommand_from install list remove help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from install" -l name -r
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from install" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from install" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from list" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from remove" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from remove" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install extension from a git URL'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from help" -f -a "list" -d 'List installed extensions'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove an installed extension'
complete -c tok0 -n "__fish_tok0_using_subcommand ext; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -f -a "on" -d 'Enable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -f -a "off" -d 'Disable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -f -a "status" -d 'Show current telemetry status'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and not __fish_seen_subcommand_from on off status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from on" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from on" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from on" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from off" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from off" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from off" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from status" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from help" -f -a "on" -d 'Enable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from help" -f -a "off" -d 'Disable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current telemetry status'
complete -c tok0 -n "__fish_tok0_using_subcommand telemetry; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -f -a "login" -d 'Login with API token'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -f -a "status" -d 'Show authentication status'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -f -a "logout" -d 'Remove stored credentials and disable cloud reporting'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and not __fish_seen_subcommand_from login status logout help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from login" -l token -d 'API token (or set TOK0_API_KEY env var)' -r
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from login" -l api-url -d 'Cloud API URL' -r
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from login" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from login" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from status" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from logout" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from logout" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from logout" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "login" -d 'Login with API token'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show authentication status'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "logout" -d 'Remove stored credentials and disable cloud reporting'
complete -c tok0 -n "__fish_tok0_using_subcommand auth; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and not __fish_seen_subcommand_from team help" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and not __fish_seen_subcommand_from team help" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and not __fish_seen_subcommand_from team help" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and not __fish_seen_subcommand_from team help" -f -a "team" -d 'Show team savings summary'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and not __fish_seen_subcommand_from team help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and __fish_seen_subcommand_from team" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and __fish_seen_subcommand_from team" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and __fish_seen_subcommand_from team" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and __fish_seen_subcommand_from help" -f -a "team" -d 'Show team savings summary'
complete -c tok0 -n "__fish_tok0_using_subcommand cloud; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand completions" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand completions" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand completions" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand trust" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand trust" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand trust" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand untrust" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand untrust" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand untrust" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand verify" -s v -l verbose -d 'Increase verbosity (-v, -vv, -vvv)'
complete -c tok0 -n "__fish_tok0_using_subcommand verify" -s u -l ultra-compact -d 'Ultra-compact output mode'
complete -c tok0 -n "__fish_tok0_using_subcommand verify" -s h -l help -d 'Print help'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "stats" -d 'Token savings analytics'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "git" -d 'Git operations'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "read" -d 'Smart file reading'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "ls" -d 'Directory listing'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "grep" -d 'Search files'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "find" -d 'Find files'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "diff" -d 'File diff'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "smart" -d 'Smart code summary'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "proxy" -d 'Proxy passthrough (no filtering, tracking only)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "status" -d 'Show tok0 status: version, hooks, savings, trust, extensions'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "doctor" -d 'Diagnose configuration + hook-health problems'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "rule" -d 'Inspect and test compression rules'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "init" -d 'Initialize hooks for AI tools'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "update" -d 'Check for updates'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "discover" -d 'Discover missed savings opportunities'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "rewrite" -d 'Rewrite command (used by hooks)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "profile" -d 'Profile compression pipeline timing'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "ext" -d 'Manage extension rule packs'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "telemetry" -d 'Control anonymous telemetry (on/off/status)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "auth" -d 'Authenticate with tok0 cloud for team analytics'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "cloud" -d 'View team dashboard (requires auth)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "completions" -d 'Generate shell completions'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "trust" -d 'Trust a project directory for local filter rules'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "untrust" -d 'Remove trust from a project directory'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "verify" -d 'Verify hook file integrity'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and not __fish_seen_subcommand_from stats git read ls grep find diff smart proxy status doctor rule init update discover rewrite profile ext telemetry auth cloud completions trust untrust verify help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from rule" -f -a "list" -d 'List all active rules (builtin + extensions + project-local)'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from rule" -f -a "show" -d 'Show full config for a single rule by name'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from rule" -f -a "test" -d 'Apply a rule to stdin and print the before/after savings'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from ext" -f -a "install" -d 'Install extension from a git URL'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from ext" -f -a "list" -d 'List installed extensions'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from ext" -f -a "remove" -d 'Remove an installed extension'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from telemetry" -f -a "on" -d 'Enable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from telemetry" -f -a "off" -d 'Disable anonymous telemetry'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from telemetry" -f -a "status" -d 'Show current telemetry status'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "login" -d 'Login with API token'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "status" -d 'Show authentication status'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from auth" -f -a "logout" -d 'Remove stored credentials and disable cloud reporting'
complete -c tok0 -n "__fish_tok0_using_subcommand help; and __fish_seen_subcommand_from cloud" -f -a "team" -d 'Show team savings summary'
